matrix:
  include:
    - language: node_js
      before_install:
        - cd server/
      install:
        - yarn install
      script:
        - yarn test
    - language: java
      before_install:
        - cd server/
        - nvm install 10.10.0
        - nvm use 10.10.0
        - yarn install
        - yarn start &
        - sleep 3
        - cd ../app/
