matrix:
  include:
    - language: node_js
      before_install:
        - cd server/
      install:
        - yarn install
      script:
        - yarn test
    - language: java
      before_install:
        - cd server/
        - curl -o ~/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh # update nvm
        - bash -c "nvm use 10.10.0"
        - yarn install
        - yarn start
        - sleep 3
        - cd ../app/
