matrix:
  include:
    - language: node_js
      before_install:
        - cd server/
      install:
        - yarn install
      script:
        - yarn test
    - language: java
      before_install:
        - cd server/
        - yarn install
        - yarn start
        - sleep 3
        - cd ../app/
